# Site
name: 'Duc-Tri VO'
description: 'Discover my personal website showcasing innovative projects, research, and insights in automation, control systems, and engineering.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
# disqus: 'demowebsite'
email: 'duc-tri.vo@outlook.fr'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Resume
title: Résumé
profile_img: /assets/images/resume/photo.jpg
icon_img: /assets/images/resume/icon.webp

# name: "Your Name Here"
# job: "À la recherche d'un poste d'Ingénieur-Chercheur spécialisé en Analyse de Données, Contrôle-Commande, Développement Logiciel ou Systèmes Embarqués"

phone_number: +33 07 65 80 35 49
address: Valence, France
email: duc-tri.vo@outlook.fr
linkedin_username: voductri97
github_username: ductrivo
instagram_username: instagram
twitter_username: twitter
facebook_username: facebook
youtube_username: ductrivo.official
blog_url: https://ductrivo.github.io



# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    ductri:
      name:           Duc-Tri
      site:           https://ductrivo.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Duc-Tri, the author of this site. I hope you like it!"
      email:          duc-tri.vo@outlook.fr
      # twitter:        https://twitter.com/wowthemesnet

    # sal:
    #   name:           Sal
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar1.jpg
    #   bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
    #   email:          wowthemesnet@gmail.com
    #   twitter:        https://twitter.com/wowthemesnet

    # jane:
    #   name:           Jane
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar2.jpg
    #   bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    #   email:          fakemail@gmail.com
    #   twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]