# Site
name: 'Duc-Tri VO'
description: "ùóòxpertise partag√©e pour la recherche, l'√©ducation, le d√©ploiement, la communaut√© et l'ouverture. Discover projects and research in automation, control systems, embedded systems, predictive control, and programming‚Äîinsights into smart engineering and real-time optimization."
logo: 'assets/images/avatar1.jpg'
favicon: 'assets/images/favicon_VDT.png'
baseurl: ''
# disqus: 'demowebsite'
email: 'duc-tri.vo@outlook.fr'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Resume
title_resume: R√©sum√©
profile_img: /assets/images/resume/photo.jpg
icon_img: /assets/images/resume/icon.webp

# name: "Your Name Here"
job: "Ing√©nieur en Informatique Industrielle, Automatisation, et Digitalisation"
phone_number: +33 07 65 80 35 49
address: Valence, France
# email: "duc-tri.vo@outlook.fr"
linkedin_username: voductri97
github_username: ductrivo
instagram_username: instagram
twitter_username: twitter
facebook_username: facebook
youtube_username: ductrivo.official
blog_url: https://ductrivo.github.io

excerpt_separator: "<!-- excerpt -->"

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-toc
authors:
    ductri:
      name:           Duc-Tri
      site:           https://ductrivo.github.io
      avatar:         "https://i.imgur.com/QSMPgex.jpg"
      bio:            "Hi, I am Duc-Tri, the author of this site. I hope you like it!"
      email:          duc-tri.vo@outlook.fr
      # twitter:        https://twitter.com/wowthemesnet

    # sal:
    #   name:           Sal
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar1.jpg
    #   bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
    #   email:          wowthemesnet@gmail.com
    #   twitter:        https://twitter.com/wowthemesnet

    # jane:
    #   name:           Jane
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar2.jpg
    #   bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    #   email:          fakemail@gmail.com
    #   twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10


toc:
  min_level: 2      # Minimum heading level (h2)
  max_level: 4      # Maximum heading level (h4)
  no_toc_section_class: no_toc  # class to exclude from toc
  list_class: toc-list
  sublist_class: toc-sublist
  item_class: toc-item
  item_prefix: toc-

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]